"""Regenerate the original, non-copyrighted 100 ms stereo test tone with FFmpeg.

Only fixture generation needs FFmpeg; tests consume the committed bytes offline.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path
import struct
import subprocess
import wave

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--ffmpeg", required=True)
args = parser.parse_args()
root = Path(__file__).resolve().parent
sample_rate, frame_count = 48000, 4800
pcm = b"".join(struct.pack("<hh", *[
    round(8192 * math.sin(2 * math.pi * frequency * frame / sample_rate))
    for frequency in (440, 660)]) for frame in range(frame_count))
with wave.open(str(root / "tone.wav"), "wb") as output:
    output.setparams((2, 2, sample_rate, frame_count, "NONE", "not compressed"))
    output.writeframes(pcm)
formats = {
    "tone.flac": ["-c:a", "flac"],
    "tone.mp3": ["-c:a", "libmp3lame", "-b:a", "128k", "-write_xing", "1"],
    "tone-vorbis.ogg": ["-c:a", "libvorbis", "-q:a", "4"],
    "tone-opus.opus": ["-c:a", "libopus", "-b:a", "96k", "-vbr", "off"],
}
for name, options in formats.items():
    subprocess.run([args.ffmpeg, "-nostdin", "-hide_banner", "-loglevel", "error", "-y",
                    "-i", str(root / "tone.wav"), "-map_metadata", "-1",
                    "-fflags", "+bitexact", "-flags:a", "+bitexact", *options,
                    str(root / name)], check=True)
version = subprocess.check_output([args.ffmpeg, "-version"], text=True).splitlines()[0]
manifest = {"source": "Original mathematical sine waves; generated by generate.py, CC0-1.0",
            "encoder": version, "sampleRate": sample_rate, "channels": 2, "sourceFrames": frame_count,
            "sha256": {name: hashlib.sha256((root / name).read_bytes()).hexdigest()
                       for name in ["tone.wav", *formats]}}
(root / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
print(json.dumps(manifest, indent=2))
