#pragma once

#include <tina/core/base/Types.hpp>

#include <compare>
#include <cstddef>
#include <optional>
#include <span>
#include <string>
#include <vector>

namespace Tina::Task {
class ITaskSystem;
}

namespace Tina::Save {

inline constexpr Core::u32 DefaultSaveSlotCapacity = 16;
inline constexpr Core::u32 MaxSaveSlotCapacity = 1024;
inline constexpr Core::u64 DefaultMaxSavePayloadBytes = 16ULL * 1024ULL * 1024ULL;
inline constexpr Core::u64 MaxSavePayloadBytes = 128ULL * 1024ULL * 1024ULL;
inline constexpr Core::usize MaxSaveGameIdBytes = 128;
inline constexpr Core::usize MaxSaveDisplayNameBytes = 512;

struct SaveSlotId final {
    Core::u32 value = 0;

    auto operator<=>(const SaveSlotId&) const = default;
};

enum class SaveStorageCopy : Core::u8 {
    Primary = 1,
    Backup = 2,
};

enum class SaveCopyState : Core::u8 {
    Missing = 0,
    Valid = 1,
    Corrupt = 2,
    Incompatible = 3,
};

enum class SaveSlotHealth : Core::u8 {
    Empty = 0,
    Healthy = 1,
    PrimaryOnly = 2,
    RecoverableFromBackup = 3,
    Unrecoverable = 4,
};

struct SaveStoreConfig final {
    // UTF-8 directory owned by this product. Slot filenames are generated by
    // SaveStore, so caller-controlled text never becomes a path component.
    std::string rootDirectoryUtf8{};
    // Stable product identity embedded in every envelope. It is not a display name.
    std::string gameId{};
    Core::u32 slotCapacity = DefaultSaveSlotCapacity;
    Core::u64 maxPayloadBytes = DefaultMaxSavePayloadBytes;
    // Optional. Required only by beginSave/beginLoad/beginList.
    Task::ITaskSystem* taskSystem = nullptr;
};

struct SaveStorePaths final {
    std::string primaryPathUtf8{};
    std::string backupPathUtf8{};
};

struct SaveWriteRequest final {
    SaveSlotId slot{};
    Core::u32 dataVersion = 0;
    std::string displayName{};
    std::span<const std::byte> payload{};
    Core::u64 playTimeMilliseconds = 0;
};

struct SaveSlotMetadata final {
    SaveSlotId slot{};
    Core::u32 dataVersion = 0;
    Core::u64 revision = 0;
    Core::u64 savedAtUnixMilliseconds = 0;
    Core::u64 playTimeMilliseconds = 0;
    std::string gameId{};
    std::string displayName{};
    Core::u64 payloadBytes = 0;

    friend bool operator==(const SaveSlotMetadata&, const SaveSlotMetadata&) = default;
};

struct SaveWriteResult final {
    SaveSlotMetadata metadata{};
    bool backupUpdated = false;
    bool replacedCorruptPrimary = false;
};

struct SaveLoadOptions final {
    bool allowBackupFallback = true;
};

struct SaveLoadResult final {
    SaveSlotMetadata metadata{};
    std::vector<std::byte> payload{};
    SaveStorageCopy source = SaveStorageCopy::Primary;
    SaveSlotHealth health = SaveSlotHealth::Empty;
};

struct SaveSlotSummary final {
    SaveSlotId slot{};
    SaveCopyState primaryState = SaveCopyState::Missing;
    SaveCopyState backupState = SaveCopyState::Missing;
    SaveSlotHealth health = SaveSlotHealth::Empty;
    std::optional<SaveStorageCopy> selectedCopy{};
    std::optional<SaveSlotMetadata> metadata{};
};

struct SaveDeleteResult final {
    SaveSlotId slot{};
    bool primaryDeleted = false;
    bool backupDeleted = false;
};

struct SaveRepairResult final {
    SaveSlotMetadata metadata{};
    bool repaired = false;
};

} // namespace Tina::Save
