#ifndef TINA_FRAMEWORK_NATIVEWINDOW_HPP
#define TINA_FRAMEWORK_NATIVEWINDOW_HPP

#include <bx/bx.h>
#if BX_PLATFORM_LINUX
#define GLFW_EXPOSE_NATIVE_X11
#elif BX_PLATFORM_WINDOWS
#define GLFW_EXPOSE_NATIVE_WIN32
#elif BX_PLATFORM_OSX
#define GLFW_EXPOSE_NATIVE_COCOA
#endif
#include <GLFW/glfw3native.h>

#endif
