add_subdirectory(null)
add_subdirectory(asset)
add_subdirectory(2d)
add_subdirectory(2d_tilemap)
add_subdirectory(3d)

if (TINA_BUILD_PHYSICS2D)
    add_subdirectory(physics2d_bench)
endif ()

if(TINA_BUILD_PLATFORM_GLFW)
    add_subdirectory(platform)
endif()

if(TINA_BUILD_PLATFORM_GLFW AND TINA_BUILD_RENDER_BGFX)
    add_subdirectory(desktop)
    add_subdirectory(3d_bgfx)
    add_subdirectory(2d_bgfx)
    add_subdirectory(2d_catalog)
    add_subdirectory(2d_tilemap_bgfx)
endif()
