// Generated by tools/editor_icons/cook_editor_icons.py. Do not edit.
#pragma once

#include <tina/core/base/Types.hpp>

#include <array>

namespace Tina::EditorApp::WorkspaceInternal {

inline constexpr Core::u32 EditorIconLogicalExtent = 18U;
inline constexpr Core::u32 EditorIconRasterScale = 2U;
inline constexpr Core::u32 EditorIconRasterExtent = 36U;
inline constexpr Core::u32 EditorIconRasterGutter = 2U;

enum class EditorIcon : Core::u8 {
    Play,
    Pause,
    Step,
    Stop,
    Undo,
    Redo,
    Save,
    SaveAs,
    Select,
    Move,
    Rotate,
    Scale,
    Add,
    Duplicate,
    Delete,
    Focus,
    Reparent,
    Root,
    Paint,
    Erase,
    World,
    Snap,
    FrameAll,
    ZoomOut,
    ZoomIn,
    Close,
    Refresh,
    Open,
    ChevronLeft,
    ChevronRight,
    ChevronDown,
    MoveLeft,
    MoveRight,
    Cook,
    Apply,
    Import,
    Search,
    Count,
};

inline constexpr Core::u32 EditorIconCount =
    static_cast<Core::u32>(EditorIcon::Count);
inline constexpr Core::u32 EditorIconAtlasWidth =
    EditorIconRasterExtent * EditorIconCount;
inline constexpr Core::u32 EditorIconAtlasHeight = EditorIconRasterExtent;

struct EditorIconAtlasRect final {
    Core::u32 x = 0U;
    Core::u32 y = 0U;
    Core::u32 width = 0U;
    Core::u32 height = 0U;
};

inline constexpr std::array<EditorIconAtlasRect, EditorIconCount>
    EditorIconAtlasRects{{
        EditorIconAtlasRect{
            .x = 0U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 1U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 2U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 3U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 4U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 5U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 6U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 7U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 8U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 9U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 10U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 11U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 12U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 13U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 14U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 15U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 16U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 17U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 18U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 19U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 20U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 21U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 22U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 23U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 24U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 25U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 26U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 27U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 28U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 29U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 30U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 31U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 32U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 33U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 34U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 35U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
        EditorIconAtlasRect{
            .x = 36U * EditorIconRasterExtent,
            .y = 0U,
            .width = EditorIconRasterExtent,
            .height = EditorIconRasterExtent,
        },
    }};

} // namespace Tina::EditorApp::WorkspaceInternal
