    set(WARNING_OPTIONS)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        list(APPEND WARNING_OPTIONS "-Wall")
        list(APPEND WARNING_OPTIONS "-Wextra")
        list(APPEND WARNING_OPTIONS "-Wno-c++98-compat")
        list(APPEND WARNING_OPTIONS "-Wdocumentation")
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        list(APPEND WARNING_OPTIONS "-Wall")
        list(APPEND WARNING_OPTIONS "-Wextra")
        list(APPEND WARNING_OPTIONS "-Wno-unknown-pragmas")
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        list(APPEND WARNING_OPTIONS "/W4")
    endif ()
    target_compile_options(${PROJECT_NAME} PRIVATE ${WARNING_OPTIONS})
    set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_WARNING_AS_ERROR FALSE)