# Invoked by a generated build rule, never by the game. This is rollback-safe
# directory promotion, not a claim of concurrent-reader atomic directory swap.
if(NOT IS_DIRECTORY "${TINA_CATALOG_PARENT}" OR NOT TINA_CATALOG_RELATIVE OR
   NOT EXISTS "${TINA_CATALOG_COOKER}")
    message(FATAL_ERROR "Catalog cook requires an existing product directory and host cooker")
endif()
file(REAL_PATH "${TINA_CATALOG_PARENT}" parent)
set(catalog "${parent}/${TINA_CATALOG_RELATIVE}")
set(stage "${catalog}.tina-stage")
set(backup "${catalog}.tina-backup")

function(tina_validate_catalog_owned_path path)
    cmake_path(ABSOLUTE_PATH path NORMALIZE OUTPUT_VARIABLE absolute)
    cmake_path(IS_PREFIX parent "${absolute}" NORMALIZE inside)
    if(NOT inside OR absolute STREQUAL parent)
        message(FATAL_ERROR "Catalog output escapes its product directory: ${path}")
    endif()
    # Resolve an existing ancestor before creating or recursively removing any
    # directory. A junction/symlink must not redirect a managed sibling outside it.
    set(ancestor "${absolute}")
    while(NOT EXISTS "${ancestor}")
        cmake_path(GET ancestor PARENT_PATH ancestor)
    endwhile()
    file(REAL_PATH "${ancestor}" resolved)
    cmake_path(IS_PREFIX parent "${resolved}" NORMALIZE inside)
    if(NOT inside)
        message(FATAL_ERROR "Catalog output follows a link outside its product directory: ${path}")
    endif()
endfunction()

function(tina_remove_catalog_output path)
    tina_validate_catalog_owned_path("${path}")
    file(REMOVE_RECURSE "${path}")
    if(EXISTS "${path}")
        message(FATAL_ERROR "Could not remove managed cook output: ${path}")
    endif()
endfunction()

function(tina_move_catalog_output source destination output)
    tina_validate_catalog_owned_path("${source}")
    tina_validate_catalog_owned_path("${destination}")
    file(RENAME "${source}" "${destination}" RESULT result)
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

foreach(path IN ITEMS "${catalog}" "${stage}" "${backup}")
    tina_validate_catalog_owned_path("${path}")
endforeach()
if(EXISTS "${backup}" AND NOT EXISTS "${catalog}")
    tina_move_catalog_output("${backup}" "${catalog}" restored)
    if(NOT restored STREQUAL "0")
        message(FATAL_ERROR "Cannot recover the previous cooked catalog: ${restored}")
    endif()
endif()
if(EXISTS "${backup}")
    if(NOT EXISTS "${catalog}/manifest.tmnft")
        message(FATAL_ERROR "Preserving backup because the current catalog has no manifest")
    endif()
    tina_remove_catalog_output("${backup}")
endif()
if(EXISTS "${stage}")
    tina_remove_catalog_output("${stage}")
endif()
get_filename_component(output_parent "${catalog}" DIRECTORY)
file(MAKE_DIRECTORY "${output_parent}")
execute_process(COMMAND "${TINA_CATALOG_COOKER}" --out "${stage}" ${TINA_CATALOG_ARGS}
    RESULT_VARIABLE cooked TIMEOUT 300)
if(NOT cooked STREQUAL "0" OR NOT EXISTS "${stage}/manifest.tmnft")
    tina_remove_catalog_output("${stage}")
    message(FATAL_ERROR "Catalog cook failed (${cooked}); the previous published catalog is unchanged")
endif()
if(EXISTS "${catalog}")
    tina_move_catalog_output("${catalog}" "${backup}" preserved)
    if(NOT preserved STREQUAL "0")
        tina_remove_catalog_output("${stage}")
        message(FATAL_ERROR "Cannot preserve the current catalog before promotion: ${preserved}")
    endif()
endif()
tina_move_catalog_output("${stage}" "${catalog}" promoted)
if(NOT promoted STREQUAL "0")
    if(EXISTS "${backup}")
        tina_move_catalog_output("${backup}" "${catalog}" restored)
        if(NOT restored STREQUAL "0")
            message(FATAL_ERROR "Catalog promotion failed; backup retained at ${backup}: ${restored}")
        endif()
    endif()
    tina_remove_catalog_output("${stage}")
    message(FATAL_ERROR "Catalog promotion failed (${promoted}); previous content restored")
endif()
if(EXISTS "${backup}")
    tina_remove_catalog_output("${backup}")
endif()
message(STATUS "Published cooked catalog: ${catalog}")
