function(tina_verify_installed_targets)
    set(tina_targets ${ARGN})
    list(REMOVE_DUPLICATES tina_targets)

    foreach(tina_target IN LISTS tina_targets)
        if(NOT TARGET ${tina_target})
            message(FATAL_ERROR "The Tina package is missing declared target ${tina_target}")
        endif()

        get_target_property(tina_target_includes ${tina_target} INTERFACE_INCLUDE_DIRECTORIES)
        if(NOT tina_target_includes OR tina_target_includes MATCHES "-NOTFOUND$")
            continue()
        endif()
        foreach(tina_include IN LISTS tina_target_includes)
            if(DEFINED TINA_FORBIDDEN_SOURCE_DIR AND NOT TINA_FORBIDDEN_SOURCE_DIR STREQUAL "")
                cmake_path(IS_PREFIX TINA_FORBIDDEN_SOURCE_DIR "${tina_include}" NORMALIZE tina_uses_source_include)
                if(tina_uses_source_include)
                    message(FATAL_ERROR "${tina_target} leaks source-tree include directory ${tina_include}")
                endif()
            endif()
            if(DEFINED TINA_EXPECTED_INSTALL_PREFIX AND NOT TINA_EXPECTED_INSTALL_PREFIX STREQUAL "")
                cmake_path(IS_PREFIX TINA_EXPECTED_INSTALL_PREFIX "${tina_include}" NORMALIZE tina_uses_install_prefix)
                if(NOT tina_uses_install_prefix)
                    message(FATAL_ERROR
                        "${tina_target} uses include directory outside the install prefix: ${tina_include}")
                endif()
            endif()
        endforeach()
    endforeach()
endfunction()

function(tina_verify_backend_neutral_game_sdk)
    if(NOT TARGET Tina::GameSDK)
        message(FATAL_ERROR "The Tina package does not provide Tina::GameSDK")
    endif()

    get_target_property(tina_game_sdk_links Tina::GameSDK INTERFACE_LINK_LIBRARIES)
    foreach(tina_adapter IN LISTS Tina_ADAPTER_TARGETS)
        if(tina_adapter IN_LIST tina_game_sdk_links)
            message(FATAL_ERROR "Tina::GameSDK unexpectedly links backend adapter ${tina_adapter}")
        endif()
    endforeach()
endfunction()
